-- ============================================================
-- IPSS - Intelligent Product Scheduling System
-- Database Schema for Supabase (PostgreSQL)
-- ============================================================
-- Run this script in the Supabase SQL Editor if you need to
-- initialize or recreate the required application tables.

-- Drop existing tables in reverse dependency order (optional)
-- DROP TABLE IF EXISTS activities CASCADE;
-- DROP TABLE IF EXISTS schedules CASCADE;
-- DROP TABLE IF EXISTS orders CASCADE;
-- DROP TABLE IF EXISTS machines CASCADE;
-- DROP TABLE IF EXISTS products CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- 1. Users Table
-- Stores operator and administrator accounts with hashed passwords
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'OPERATOR',
    designation VARCHAR(100) DEFAULT 'Staff',
    department VARCHAR(100) DEFAULT 'Production',
    employee_id VARCHAR(50) DEFAULT 'IPSS-001',
    phone VARCHAR(30) DEFAULT '',
    dob VARCHAR(30) DEFAULT '',
    gender VARCHAR(20) DEFAULT 'Male',
    address VARCHAR(255) DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Products Table
-- Master catalog of manufactured goods
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(100) NOT NULL,
    processing_time DOUBLE PRECISION NOT NULL,
    preferred_line VARCHAR(50) DEFAULT 'All Machines',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Machines Table
-- Factory production lines and machines
CREATE TABLE IF NOT EXISTS machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_name VARCHAR(100) NOT NULL UNIQUE,
    capacity INT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Available',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Orders Table
-- Production batch requests
-- Foreign keys: product_id -> products.id, user_id -> users.id
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(50) NOT NULL UNIQUE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INT NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
    deadline VARCHAR(50) NOT NULL,
    processing_time DOUBLE PRECISION DEFAULT 0.05,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Schedules Table
-- Optimized timeline allocations
-- Foreign keys: machine_id -> machines.id, order_id -> orders.id
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    start_time VARCHAR(50) NOT NULL,
    end_time VARCHAR(50) NOT NULL,
    priority VARCHAR(20) DEFAULT 'Medium',
    status VARCHAR(50) DEFAULT 'Scheduled',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Activities Table
-- Shopfloor event logs
CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    activity_type VARCHAR(20) DEFAULT 'info',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
